### ISSUE TITLE
Create a release

### ISSUE THREAD

**Issue by FFY00** [pothosware/SoapyNetSDR#1]
Would it be possible to create a release?

**Comment by guruofquality** [comment]
Im going to wait for https://github.com/pothosware/SoapyNetSDR/issues/4, but otherwise a good idea

**Comment by FFY00** [comment]
Guess this is ready then.

**Comment by guruofquality** [comment]
https://github.com/pothosware/SoapyNetSDR/releases

**Comment by FFY00** [comment]
Thanks! Released in the Acrhlinux repos :)
