### ISSUE TITLE
check in a license file

### ISSUE THREAD

**Issue by guruofquality** [pothosware/SoapyNetSDR#4]
@righthalfplane can you give the project some kind of LICENSE.txt file? We are going to need that to get into various packaging systems, etc...

**Comment by FFY00** [comment]
Bumping as it is needed for #1.

**Comment by FFY00** [comment]
Wait, nevermind. It is already there. @guruofquality can this be closed now?

**Comment by guruofquality** [comment]
Excellent https://github.com/pothosware/SoapyNetSDR/commit/39efeb9c702774805b75303b6777ef4db7db5612 thanks @righthalfplane
